name: compile_and_memcheck

on:
  push:
    paths:
      - ".github/workflows/*"
      - "CMakeLists.txt"
      - "includes/**"
      - "src/**"

  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/*"
      - "CMakeLists.txt"
      - "includes/**"
      - "src/**"

jobs:
  build_executable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build primary executable
        run: cmake -Bbuild -DCMAKE_BUILD_TYPE=Release && cmake --build ./build/

      - name: Exercise install
        run: sudo cmake --install ./build/

      - name: Exercise uninstall
        run: sudo rm $(cat build/install_manifest.txt) build/install_manifest.txt

        #- name: Clean up primary build
        #run: make clean

      - name: Build debug executable
        run: cmake -Bbuild -DCMAKE_BUILD_TYPE=Debug && cmake --build ./build/

        #- name: Clean up debug build
        #run: make debug_clean

  run_valgrind:
    needs: build_executable
    runs-on: ubuntu-latest
    env:
      test_files_dir: test_dir
      utils: .github/utils
    steps:
      - uses: actions/checkout@v3

      - name: Update packages
        run: sudo apt update

      - name: Install dependencies
        run: sudo apt-get -y install valgrind

      - name: Create test files
        run: sh "$utils"/init_files.sh "$test_files_dir" 10

      - name: Build debug executable
        run: cmake -Bbuild -DCMAKE_BUILD_TYPE=Debug && cmake --build ./build/

      - name: Execute Valgrind
        run: valgrind --leak-check=full --track-origins=yes --show-leak-kinds=all -s ./build/mmv "$test_files_dir"/test*
